/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Shared memory transport for graphics protocol.
 *
 * Kitty's graphics protocol unlinks the shm after reading. If we reuse the
 * same name across paints, fast scrolling races: paint N+1 opens the still-
 * existing name, overwrites N's data, then N+1's transmit fails because
 * Kitty unlinked between our open and its read. To avoid the race we rotate
 * to a fresh name on every `write` / `write_iosurface` call.
 *
 * # Warm buffer optimization
 *
 * Instead of converting BGRA->RGBA directly into freshly-mmaped shm pages
 * (which triggers thousands of zero-fill page faults), we convert into a
 * persistent warm buffer and then `write()` the result into the shm fd.
 * The warm buffer's pages stay resident across frames, so the SIMD conversion
 * writes to hot memory. The kernel `write()` handles shm page allocation
 * internally without user-space page faults.
 */
export declare class ShmGraphicBuffer {
  /** Creates a new shared memory buffer with a unique name with the provided size */
  constructor(size: number)
  /**
   * Returns the most recently rotated shm name as base64 (for the Kitty
   * graphics protocol's `t=s` payload).
   */
  get nameBase64(): string
  /**
   * Writes an image buffer to the shared memory at the specified dirty rectangle.
   * Rotates to a fresh shm name first to avoid races with Kitty's post-read unlink.
   *
   * Uses a warm intermediate buffer to avoid page faults: BGRA->RGBA conversion
   * writes to a persistent anonymous mmap (warm pages), then `write(fd)` copies
   * the result into the fresh shm fd.
   */
  write(buffer: Buffer, imageWidth: number, dirtyRect?: DirtyRect | undefined | null): void
  /**
   * Reads pixels directly from an IOSurface (delivered by Electron's
   * `useSharedTexture` paint event on macOS) into shared memory, skipping
   * the GPU→CPU readback that `image.toBitmap()` would perform.
   *
   * `surface_handle` is a Buffer wrapping an `IOSurfaceRef` pointer
   * (`event.texture.textureInfo.handle.ioSurface`).
   */
  writeIosurface(surfaceHandle: Buffer, dirtyRect?: DirtyRect | undefined | null): void
}

export interface DirtyRect {
  x: number
  y: number
  width: number
  height: number
}

/** Get the current terminal window size */
export declare function getWindowSize(): WindowSize

export interface KeyEvent {
  /** Key code in Electron accelerator format (lowercase) */
  code: string
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift' | 'meta' | 'capsLock' | 'numLock' | 'left' | 'right' | 'isAutoRepeat')[]
  /** True for keydown and repeat events, false for keyup */
  down: boolean
  /** True for keys that should have an Electron char event */
  isCharEvent: boolean
}

export interface KittyGraphics {
  id: string
  status: string
}

export declare function listenForInput(callback: (arg: TermEvent) => void, waitMs?: number | undefined | null): () => void

export interface MouseEvent {
  kind: 'mouseDown' | 'mouseUp' | 'mouseMove' | 'scrollUp' | 'scrollDown' | 'scrollLeft' | 'scrollRight'
  button?: 'left' | 'middle' | 'right' | 'fourth' | 'fifth' | null
  x: number
  y: number
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift')[]
}

export interface SupportedFeatures {
  keyboard: boolean
  images: boolean
  loadFrame: boolean
  compositeFrame: boolean
}

/** Disable previously enabled features for the terminal that are necessary for Awrit */
export declare function termDisableFeatures(features: SupportedFeatures): void

/** Enable features for the terminal that are necessary for Awrit */
export declare function termEnableFeatures(): SupportedFeatures

export interface TermEscape {
  kind: 'osc' | 'apc' | 'dcs' | 'pm'
  text: string
}

export type TermEvent =
  { eventType: 'key', keyEvent: KeyEvent } |
  { eventType: 'mouse', mouseEvent: MouseEvent } |
  { eventType: 'focus', focusGained?: boolean, focusLost?: boolean } |
  { eventType: 'resize', resize: TermResize } |
  { eventType: 'paste', paste: string } |
  { eventType: 'escape', escape: TermEscape } |
  { eventType: 'graphics', graphics: KittyGraphics }

export interface TermResize {
  columns: number
  rows: number
}

export interface WindowSize {
  cols: number
  rows: number
  width: number
  height: number
}
