name: CI
env:
  DEBUG: napi:*
  APP_NAME: glimpse-tty-native-rs
  MACOSX_DEPLOYMENT_TARGET: '10.13'
  NODE_VERSION: 22
'on':
  pull_request:
    paths:
      - 'glimpse-tty-native-rs/package.json'
      - 'glimpse-tty-native-rs/Cargo.*'
      - 'glimpse-tty-native-rs/src/**'
      - 'glimpse-tty-native-rs/build.rs'
      - 'glimpse-tty-native-rs/crates/**/*.rs'
      - 'glimpse-tty-native-rs/src/Cargo.*'
      - 'glimpse-tty-native-rs/crates/**/Cargo.*'
      - '.github/workflows/CI.yml'
  push:
    branches:
      - master
    paths:
      - 'glimpse-tty-native-rs/package.json'
      - 'glimpse-tty-native-rs/Cargo.*'
      - 'glimpse-tty-native-rs/src/**'
      - 'glimpse-tty-native-rs/build.rs'
      - 'glimpse-tty-native-rs/crates/**/*.rs'
      - 'glimpse-tty-native-rs/src/Cargo.*'
      - 'glimpse-tty-native-rs/crates/**/Cargo.*'
      - '.github/workflows/CI.yml'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            build: yarn ci --target x86_64-unknown-linux-gnu
          - host: macos-latest
            target: aarch64-apple-darwin
            build: yarn ci --target aarch64-apple-darwin
          - host: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            build: yarn ci --target aarch64-unknown-linux-gnu
    name: stable - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: glimpse-tty-native-rs
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: glimpse-tty-native-rs/yarn.lock
      - name: Install dependencies
        run: yarn install
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: glimpse-tty-native-rs/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
